// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"
	"goods/goods"
	"goods/internal/logic"
	"goods/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) Ping(ctx context.Context, in *goods.Request) (*goods.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *GoodsServer) GetGoodsByIDs(ctx context.Context, in *goods.GetGoodsByIDsRequest) (*goods.GetGoodsByIDsResponse, error) {
	l := logic.NewGetGoodsByIDsLogic(ctx, s.svcCtx)
	return l.GetGoodsByIDs(in)
}

func (s *GoodsServer) UpdateGoodsStocks(ctx context.Context, in *goods.UpdateGoodsStocksRequest) (*goods.UpdateGoodsStocksResponse, error) {
	l := logic.NewUpdateGoodsStocksLogic(ctx, s.svcCtx)
	return l.UpdateGoodsStocks(in)
}
